### ISSUE TITLE
Bug When 2 rules assigned to same identity or Endpoint.

### ISSUE THREAD

**Issue by bahmad12** [scale-tone/ThrottlingTroll#15]
for example, if user have a limit of 20 per minute and 100 per hour and 1000 per day, so we can setup 3 rules for same identity: [{PermitLimit = 20, IntervalInSeconds = 60}, {PermitLimit = 100, IntervalInSeconds = 360}, {PermitLimit = 1000, IntervalInSeconds = 8640}]

the code loops through each rule as expected, but when it register in memory it uses same key for all rules, which make it hit what ever rule limit is lowest.

**Comment by scale-tone** [comment]
Fixed in [v6.0](https://github.com/scale-tone/ThrottlingTroll/releases/tag/v6.0).
