### ISSUE TITLE
Feature Request for Azure Functions: Retrieval of Rate Limiting Values

### ISSUE THREAD

**Issue by Mxater** [scale-tone/ThrottlingTroll#18]
Recently, I have been working on implementing rate limiting in my Azure functions to better manage incoming request traffic. To achieve this, I have been using your library.

However, during my implementation, I have noticed that it is not possible to retrieve important information related to rate limiting directly from the HTTP response generated by the library. Specifically, I would like to be able to include the following headers in my function responses:

- RateLimit-Limit: The limit of allowed requests within a specific time period.
- RateLimit-Available: The number of available requests within the current rate limit.
- RateLimit-Reset-Time: The moment when the current rate limit will reset.

These headers would be extremely useful for clients and consumers of my functions to better understand and manage their requests and adjust their behavior based on the rate limit status.

Thanks

**Comment by scale-tone** [comment]
This indeed would be a useful feature, @Mxater !

**Comment by SebastianAviles** [comment]
how was with that?

**Comment by scale-tone** [comment]
Working on it, @SebastianAviles . Expect a new release next week :)

**Comment by scale-tone** [comment]
Implemented in [v6.0](https://github.com/scale-tone/ThrottlingTroll/releases/tag/v6.0).
